parameters:
    cl_archiver.archiver.entity.class: CL\Bundle\ArchiverBundle\Archiver\Entity\EntityArchiver

services:
    cl_archiver.archiver.entity:
        class: %cl_archiver.archiver.entity.class%
        arguments: [@doctrine.orm.entity_manager]
